//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen-v0.36. DO NOT EDIT.

package v1alpha1

import (
	v2 "ocm.software/open-component-model/bindings/go/descriptor/v2"
	runtime "ocm.software/open-component-model/bindings/go/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddS3Resource) DeepCopyInto(out *AddS3Resource) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(AddS3ResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(AddS3ResourceOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddS3Resource.
func (in *AddS3Resource) DeepCopy() *AddS3Resource {
	if in == nil {
		return nil
	}
	out := new(AddS3Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *AddS3Resource) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddS3ResourceOutput) DeepCopyInto(out *AddS3ResourceOutput) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddS3ResourceOutput.
func (in *AddS3ResourceOutput) DeepCopy() *AddS3ResourceOutput {
	if in == nil {
		return nil
	}
	out := new(AddS3ResourceOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddS3ResourceSpec) DeepCopyInto(out *AddS3ResourceSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	out.File = in.File
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddS3ResourceSpec.
func (in *AddS3ResourceSpec) DeepCopy() *AddS3ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(AddS3ResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetS3Resource) DeepCopyInto(out *GetS3Resource) {
	*out = *in
	out.Type = in.Type
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(GetS3ResourceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Output != nil {
		in, out := &in.Output, &out.Output
		*out = new(GetS3ResourceOutput)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetS3Resource.
func (in *GetS3Resource) DeepCopy() *GetS3Resource {
	if in == nil {
		return nil
	}
	out := new(GetS3Resource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyTyped is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Typed.
func (in *GetS3Resource) DeepCopyTyped() runtime.Typed {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetS3ResourceOutput) DeepCopyInto(out *GetS3ResourceOutput) {
	*out = *in
	out.File = in.File
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetS3ResourceOutput.
func (in *GetS3ResourceOutput) DeepCopy() *GetS3ResourceOutput {
	if in == nil {
		return nil
	}
	out := new(GetS3ResourceOutput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GetS3ResourceSpec) DeepCopyInto(out *GetS3ResourceSpec) {
	*out = *in
	if in.Resource != nil {
		in, out := &in.Resource, &out.Resource
		*out = new(v2.Resource)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GetS3ResourceSpec.
func (in *GetS3ResourceSpec) DeepCopy() *GetS3ResourceSpec {
	if in == nil {
		return nil
	}
	out := new(GetS3ResourceSpec)
	in.DeepCopyInto(out)
	return out
}
