//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by jsonschemagen. DO NOT EDIT.

package v1alpha1

import (
	_ "embed"
)

//go:embed schemas/AddS3Resource.schema.json
var schemaAddS3Resource []byte

//go:embed schemas/AddS3ResourceOutput.schema.json
var schemaAddS3ResourceOutput []byte

//go:embed schemas/AddS3ResourceSpec.schema.json
var schemaAddS3ResourceSpec []byte

//go:embed schemas/GetS3Resource.schema.json
var schemaGetS3Resource []byte

//go:embed schemas/GetS3ResourceOutput.schema.json
var schemaGetS3ResourceOutput []byte

//go:embed schemas/GetS3ResourceSpec.schema.json
var schemaGetS3ResourceSpec []byte

// JSONSchema returns the JSON Schema for AddS3Resource.
func (AddS3Resource) JSONSchema() []byte {
	return schemaAddS3Resource
}

// JSONSchema returns the JSON Schema for AddS3ResourceOutput.
func (AddS3ResourceOutput) JSONSchema() []byte {
	return schemaAddS3ResourceOutput
}

// JSONSchema returns the JSON Schema for AddS3ResourceSpec.
func (AddS3ResourceSpec) JSONSchema() []byte {
	return schemaAddS3ResourceSpec
}

// JSONSchema returns the JSON Schema for GetS3Resource.
func (GetS3Resource) JSONSchema() []byte {
	return schemaGetS3Resource
}

// JSONSchema returns the JSON Schema for GetS3ResourceOutput.
func (GetS3ResourceOutput) JSONSchema() []byte {
	return schemaGetS3ResourceOutput
}

// JSONSchema returns the JSON Schema for GetS3ResourceSpec.
func (GetS3ResourceSpec) JSONSchema() []byte {
	return schemaGetS3ResourceSpec
}
